#!/usr/bin/env python3

import feedparser
from bs4 import BeautifulSoup
from termcolor import colored


URL = 'https://www.archlinux.org/feeds/news/'


def main(args=None):

    for entry in feedparser.parse(URL).entries[:3]:
        print("=======================================================")
        print(colored(BeautifulSoup(entry.title, "html.parser").get_text(), 'red'), end='   ')
        print(colored(BeautifulSoup(entry.published, "html.parser").get_text(), 'cyan'))
        print(colored(BeautifulSoup(entry.summary, "html.parser").get_text(), 'yellow'))




if __name__ == '__main__':
    main()
